name: Snapshot Images

on:
  workflow_call:
    inputs:
      name:
        description: 'The name of the image'
        required: true
        type: string
      runId:
        description: 'A workflow runId'
        required: true
        type: string
      tag:
        description: 'A tag to add to the snapshot image'
        required: true
        type: string
  workflow_dispatch:
    inputs:
      name:
        description: 'The name of the image'
        default: 'server'
        type: string
      runId:
        description: 'A workflow runId'
        required: true
        type: string
      tag:
        description: 'A tag to add to the snapshot image'
        required: true
        type: string

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4.1.7
        with:
          run-id: '${{ inputs.runId }}'
          name: infinispan-dist
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract artifact
        id: extract_artifact
        run: |
          unzip -q infinispan-*-src.zip
          SRCROOT=$(find . -maxdepth 1 -type d -name '*src')
          echo "srcroot=$SRCROOT" >> $GITHUB_OUTPUT
          mv infinispan-server-*.zip "$SRCROOT"/server/image/infinispan-server.zip

      - name: Build image
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          build-args: |
            BRAND_VERSION=${{ inputs.runId }}
            BRAND_NAME=Infinispan
            JDK_DIST=src/main/docker/adoptium
            SERVER_DIST=infinispan-server.zip
          containerfiles: ./${{ steps.extract_artifact.outputs.srcroot }}/server/image/src/main/docker/Dockerfile
          context: ./${{ steps.extract_artifact.outputs.srcroot }}/server/image
          image: ${{ inputs.name }}
          platforms: linux/amd64, linux/arm64
          tags: ${{ inputs.tag }}

      - name: Log in to Quay.io
        uses: redhat-actions/podman-login@v1
        with:
          username:  ${{ secrets.QUAY_USERNAME_TEST }}
          password: ${{ secrets.QUAY_TOKEN_TEST }}
          registry: quay.io

      - name: Push to Quay.io
        id: push-to-quay
        uses: redhat-actions/push-to-registry@v2
        with:
          registry: quay.io/infinispan-test
          image: server
          tags: ${{ steps.build-image.outputs.tags }}

      - name: Print Quay.io image url
        run: echo "Image pushed to ${{ steps.push-to-quay.outputs.registry-paths }}"
